[[drone]]
id = 0
connected_node_ids = [3, 7, 10]
pdr = 0.05

[[drone]]
id = 1
connected_node_ids = [4, 8, 13]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [5, 9, 14]
pdr = 0.00

[[drone]]
id = 3
connected_node_ids = [0, 6, 11]
pdr = 0.50

[[drone]]
id = 4
connected_node_ids = [1, 7]
pdr = 0.50

[[drone]]
id = 5
connected_node_ids = [2, 8]
pdr = 0.00

[[drone]]
id = 6
connected_node_ids = [3, 9]
pdr = 0.00

[[drone]]
id = 7
connected_node_ids = [0, 4, 12]
pdr = 0.00

[[drone]]
id = 8
connected_node_ids = [1, 5, 16]
pdr = 0.00

[[drone]]
id = 9
connected_node_ids = [2, 6, 15]
pdr = 0.00

[[client]]
id = 10
connected_drone_ids = [0]

[[client]]
id = 11
connected_drone_ids = [3]

[[client]]
id = 12
connected_drone_ids = [7]

[[server]]
id = 13
connected_drone_ids = [1]

[[server]]
id = 14
connected_drone_ids = [2]

[[server]]
id = 15
connected_drone_ids = [9]

[[server]]
id = 16
connected_drone_ids = [8]