[[drone]]
id = 1
connected_node_ids = [0,2,6,12,15,14,16,11]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [1,7,3]
pdr = 0.00

[[drone]]
id = 3
connected_node_ids = [2,8,4,13]
pdr = 0.00

[[drone]]
id = 4
connected_node_ids = [3,9,5]
pdr = 0.00

[[drone]]
id = 5
connected_node_ids = [4,10]
pdr = 0.00

[[drone]]
id = 6
connected_node_ids = [1,7]
pdr = 0.00

[[drone]]
id = 7
connected_node_ids = [6,2,8]
pdr = 0.00

[[drone]]
id = 8
connected_node_ids = [7,3,9]
pdr = 0.00

[[drone]]
id = 9
connected_node_ids = [8,4,10]
pdr = 0.00

[[drone]]
id = 10
connected_node_ids = [9,5,11]
pdr = 0.00

[[client]]
id = 0
connected_drone_ids = [1]

[[client]]
id = 11
connected_drone_ids = [1, 10]

[[client]]
id = 13
connected_drone_ids = [3]

[[server]]
id=12
connected_drone_ids = [1]

[[server]]
id=15
connected_drone_ids = [1]

[[server]]
id=14
connected_drone_ids = [1]

[[server]]
id=16
connected_drone_ids = [1]