[[drone]]
id = 1
connected_node_ids = [2,7]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [1,3]
pdr = 0.00

[[drone]]
id = 3
connected_node_ids = [2,4,9,10]
pdr = 0.00

[[drone]]
id = 4
connected_node_ids = [3,9,8,5]
pdr = 0.00

[[drone]]
id = 5
connected_node_ids = [4,6,8]
pdr = 0.00

[[client]]
id = 6
connected_drone_ids = [5]

[[client]]
id = 7
connected_drone_ids = [1]

[[client]]
id = 10
connected_drone_ids = [3]

[[server]]
id = 8
connected_drone_ids = [4,5]

[[server]]
id = 9
connected_drone_ids = [3,4]

