[[drone]]
id = 1
connected_node_ids = [0,2,3]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [1,4,5,6]
pdr = 0.00

[[drone]]
id = 3
connected_node_ids = [1,4,5,6]
pdr = 0.00

[[drone]]
id = 4
connected_node_ids = [2,3,7,8,9,10]
pdr = 0.00

[[drone]]
id = 5
connected_node_ids = [2,3,7,8,9,10]
pdr = 0.00

[[drone]]
id = 6
connected_node_ids = [2,3,7,8,9,10]
pdr = 0.00

[[drone]]
id = 7
connected_node_ids = [4,5,6]
pdr = 0.00

[[drone]]
id = 8
connected_node_ids = [4,5,6]
pdr = 0.00

[[drone]]
id = 9
connected_node_ids = [4,5,6]
pdr = 0.00

[[drone]]
id = 10
connected_node_ids = [4,5,6,11]
pdr = 0.00

[[client]]
id = 0
connected_drone_ids = [1]

[[server]]
id = 11
connected_drone_ids = [10]