[[drone]]
id = 1
connected_node_ids = [11, 2, 4]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [1, 5]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [2, 4, 6]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [5, 3]
pdr = 0.05

[[drone]]
id = 0
connected_node_ids = []
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 3, 5]
pdr = 1.00

[[drone]]
id = 3
connected_node_ids = [2, 6,11]
pdr = 0.14

[[client]]
id = 11
connected_drone_ids = [1]

[[client]]
id = 5
connected_drone_ids = [1]

[[server]]
id = 6
connected_drone_ids = [2, 3]